"""iceberg_spark - PySpark-compatible SQL interface on DataFusion + Iceberg Rust.

Run the same spark.sql() commands using DataFusion for query execution
and Iceberg Rust for table management, with zero JVM dependency.

Usage:
    from iceberg_spark import IcebergSession

    session = IcebergSession.builder() \\
        .catalog("rest", uri="http://localhost:8181") \\
        .build()

    df = session.sql("SELECT * FROM db.table WHERE id > 5")
    df.show()
"""

from iceberg_spark.column import Column
from iceberg_spark.dataframe import DataFrame
from iceberg_spark.functions import (
    abs,
    approx_count_distinct,
    avg,
    ceil,
    coalesce,
    col,
    collect_list,
    column,
    concat,
    concat_ws,
    count,
    count_distinct,
    current_date,
    current_timestamp,
    dayofmonth,
    exp,
    first,
    floor,
    hour,
    isnan,
    isnull,
    last,
    length,
    lit,
    log,
    lower,
    lpad,
    ltrim,
    max,
    mean,
    min,
    minute,
    month,
    nullif,
    power,
    regexp_replace,
    reverse,
    round,
    rpad,
    rtrim,
    second,
    split,
    sqrt,
    stddev,
    substring,
    sum,
    trim,
    upper,
    variance,
    when,
    year,
    # Window functions
    cume_dist,
    dense_rank,
    lag,
    lead,
    ntile,
    percent_rank,
    rank,
    row_number,
    # --- Task 7A: Aggregates + Conditionals + Window ---
    any_value,
    bool_and,
    bool_or,
    collect_set,
    corr,
    covar_pop,
    covar_samp,
    first_value,
    greatest,
    ifnull,
    isnotnull,
    last_value,
    least,
    nth_value,
    nvl,
    nvl2,
    percentile_approx,
    stddev_pop,
    var_pop,
    # --- Task 7B: String functions ---
    ascii_func,
    chr_func,
    initcap,
    instr,
    left,
    locate,
    regexp_extract,
    repeat_func,
    right,
    translate,
    # --- Task 7C: Math + Trig + Hash ---
    acos,
    asin,
    atan,
    atan2,
    cbrt,
    cos,
    cosh,
    cot,
    degrees,
    factorial,
    hex_func,
    log10,
    log1p,
    log2,
    md5,
    pmod,
    pow,
    radians,
    sha1,
    sha2,
    sign,
    signum,
    sin,
    sinh,
    tan,
    tanh,
    pi,
    e,
    # --- Task 7D: Date/Time ---
    date_format,
    date_trunc,
    dayofweek,
    dayofyear,
    make_date,
    quarter,
    to_date,
    to_timestamp,
    trunc,
    weekofyear,
    # --- Task 7E: Collection functions ---
    array,
    array_contains,
    array_distinct,
    array_join,
    array_position,
    array_remove,
    array_sort,
    array_union,
    element_at,
    explode,
    flatten,
    size,
    sort_array,
    struct_func,
    # --- Sprint 2: Date/time gaps ---
    add_months,
    date_add_func,
    date_sub,
    from_unixtime,
    last_day,
    months_between,
    next_day,
    unix_timestamp,
    # --- Sprint 1: Core missing functions ---
    bitwise_not,
    broadcast,
    expr,
    input_file_name,
    monotonically_increasing_id,
    nanvl,
    spark_partition_id,
    typedLit,
    # --- Sprint 2: Format functions ---
    format_number,
    format_string,
    # --- Sprint 2: Collection gaps ---
    array_except,
    array_intersect,
    arrays_overlap,
    create_map,
    map_keys,
    map_values,
    # --- Sprint 2: JSON functions ---
    from_json,
    schema_of_json,
    to_json,
    # --- UDF support ---
    udf,
    udaf,
)
# PySpark-compatible aliases for functions that would shadow builtins.
# Both names work: `from iceberg_spark import hex` or `from iceberg_spark import hex_func`
date_add = date_add_func
ascii = ascii_func
chr = chr_func
hex = hex_func
repeat = repeat_func
struct = struct_func

from iceberg_spark.row import Row
from iceberg_spark.catalog_api import IcebergCatalogAPI
from iceberg_spark.catalog_ops import (
    IcebergSparkError,
    TableNotFoundError,
    DDLError,
    DMLError,
    SchemaError,
)
from iceberg_spark.session import IcebergSession, IcebergSessionBuilder, RuntimeConfig
from iceberg_spark.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    ByteType,
    CharType,
    DataType,
    DateType,
    DayTimeIntervalType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    NullType,
    ShortType,
    StringType,
    StructField,
    StructType,
    TimestampNTZType,
    TimestampType,
    VarcharType,
)
from iceberg_spark.window import Window, WindowSpec
from iceberg_spark.grouped_data import GroupedData
from iceberg_spark.dataframe import DataFrameNaFunctions, DataFrameStatFunctions
from iceberg_spark.reader import DataFrameReader
from iceberg_spark.writer import DataFrameWriter
from iceberg_spark.writer_v2 import DataFrameWriterV2

__version__ = "0.1.0"

__all__ = [
    # Exceptions
    "IcebergSparkError",
    "TableNotFoundError",
    "DDLError",
    "DMLError",
    "SchemaError",
    # Session
    "IcebergSession",
    "IcebergSessionBuilder",
    "IcebergCatalogAPI",
    "RuntimeConfig",
    # DataFrame
    "DataFrame",
    "Column",
    "Row",
    "GroupedData",
    "DataFrameNaFunctions",
    "DataFrameStatFunctions",
    "DataFrameReader",
    "DataFrameWriter",
    "DataFrameWriterV2",
    "Window",
    "WindowSpec",
    # Types
    "DataType",
    "NullType",
    "BooleanType",
    "ByteType",
    "ShortType",
    "IntegerType",
    "LongType",
    "FloatType",
    "DoubleType",
    "StringType",
    "BinaryType",
    "DateType",
    "TimestampType",
    "TimestampNTZType",
    "DecimalType",
    "CharType",
    "VarcharType",
    "DayTimeIntervalType",
    "StructField",
    "StructType",
    "ArrayType",
    "MapType",
    # Functions
    "col",
    "column",
    "lit",
    "count",
    "sum",
    "avg",
    "mean",
    "min",
    "max",
    "first",
    "last",
    "count_distinct",
    "approx_count_distinct",
    "collect_list",
    "stddev",
    "variance",
    "upper",
    "lower",
    "trim",
    "ltrim",
    "rtrim",
    "length",
    "concat",
    "concat_ws",
    "substring",
    "regexp_replace",
    "split",
    "reverse",
    "lpad",
    "rpad",
    "current_date",
    "current_timestamp",
    "year",
    "month",
    "dayofmonth",
    "hour",
    "minute",
    "second",
    "abs",
    "ceil",
    "floor",
    "round",
    "sqrt",
    "log",
    "exp",
    "power",
    "when",
    "coalesce",
    "isnull",
    "isnan",
    "nullif",
    # Window functions
    "row_number",
    "rank",
    "dense_rank",
    "percent_rank",
    "cume_dist",
    "ntile",
    "lag",
    "lead",
    # Task 7A: Aggregates + Conditionals + Window
    "any_value",
    "bool_and",
    "bool_or",
    "collect_set",
    "corr",
    "covar_pop",
    "covar_samp",
    "first_value",
    "greatest",
    "ifnull",
    "isnotnull",
    "last_value",
    "least",
    "nth_value",
    "nvl",
    "nvl2",
    "percentile_approx",
    "stddev_pop",
    "var_pop",
    # Task 7B: String functions
    "ascii_func",
    "chr_func",
    "initcap",
    "instr",
    "left",
    "locate",
    "regexp_extract",
    "repeat_func",
    "right",
    "translate",
    # Task 7C: Math + Trig + Hash
    "acos",
    "asin",
    "atan",
    "atan2",
    "cbrt",
    "cos",
    "cosh",
    "cot",
    "degrees",
    "factorial",
    "hex_func",
    "log10",
    "log1p",
    "log2",
    "md5",
    "pmod",
    "pow",
    "radians",
    "sha1",
    "sha2",
    "sign",
    "signum",
    "sin",
    "sinh",
    "tan",
    "tanh",
    "pi",
    "e",
    # Task 7D: Date/Time
    "date_format",
    "date_trunc",
    "dayofweek",
    "dayofyear",
    "make_date",
    "quarter",
    "to_date",
    "to_timestamp",
    "trunc",
    "weekofyear",
    # Task 7E: Collection functions
    "array",
    "array_contains",
    "array_distinct",
    "array_join",
    "array_position",
    "array_remove",
    "array_sort",
    "array_union",
    "element_at",
    "explode",
    "flatten",
    "size",
    "sort_array",
    "struct_func",
    # Sprint 2: Date/time gaps
    "add_months",
    "date_add",
    "date_add_func",
    "date_sub",
    "from_unixtime",
    "last_day",
    "months_between",
    "next_day",
    "unix_timestamp",
    # Sprint 1: Core missing functions
    "bitwise_not",
    "broadcast",
    "expr",
    "input_file_name",
    "monotonically_increasing_id",
    "nanvl",
    "spark_partition_id",
    "typedLit",
    # Sprint 2: Format functions
    "format_number",
    "format_string",
    # Sprint 2: Collection gaps
    "array_except",
    "array_intersect",
    "arrays_overlap",
    "create_map",
    "map_keys",
    "map_values",
    # Sprint 2: JSON functions
    "from_json",
    "schema_of_json",
    "to_json",
    # UDF support
    "udf",
    "udaf",
    # PySpark-compatible aliases (shadow builtins, matching PySpark behavior)
    "ascii",
    "chr",
    "hex",
    "repeat",
    "struct",
]
